name: Build, Test & Deploy

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    name: Build Site
    runs-on: ubuntu-latest
    steps:
      - name: Checkout your repository using git
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4

      - name: Setup package manager
        uses: pnpm/action-setup@v4
        with:
          run_install: |
            - args: [--frozen-lockfile, --strict-peer-dependencies]

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          cache-dependency-path: 'pnpm-lock.yaml'
          node-version-file: '.nvmrc'
          cache: 'pnpm'

      - name: Restore Build Cache
        uses: actions/cache@5a3ec84eff668545956fd18022155c47e93e2684 # v4
        with:
          path: './node_modules/.astro'
          key: astro-cache-${{ hashFiles('pnpm-lock.yaml') }}-${{ hashFiles('src/**') }}
          restore-keys: |
            astro-cache-${{ hashFiles('pnpm-lock.yaml') }}-
            astro-cache-

      - name: Build your site
        run: pnpm run build

      - name: Deploy to Cloudflare Pages
        uses: cloudflare/wrangler-action@da0e0dfe58b7a431659754fdf3f186c529afbe65 # v3
        with:
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          gitHubToken: ${{ secrets.GITHUB_TOKEN }}
